### ISSUE TITLE
How to format time properly

### ISSUE THREAD

**Issue by korruptcow** [pre-martin/StreamDeckSimHubPlugin#113]
I have been using the  plugin and i wanted to get a remaining fuel time the issue is i tried all different ways to format it in the display format section but it didnt work

the output is 00:00:0000000

I want to bring it down to minutes and seconds only and cut off the milliseconds

Property:DataCorePlugin.Computed.Fuel_RemainingTime
Display format: I have tried 

{:mm:ss}
{4:mm:ss}
{f:0}

and a couple of other combos.
Can i get the correct way to format it.

**Comment by pre-martin** [comment]
Unfortunately, you can't.

The format would be `{:mm\:ss}`. But SimHub delivers the properties just as an "object". Therefore both plugins have no idea about the type of the property. C# (the Stream Deck plugin is written in C#) requires a valid data type for formatting. So to format something with a time string, C# expects a data type that has something to do with time.

All properties listed on https://github.com/pre-martin/SimHubPropertyServer?tab=readme-ov-file#help do have a type (e.g. the property `dcp.gd.SessionTimeLeft` is of type `timespan` and thus it is possible to format the values of this property with a time string).

But there is some hope: While writing these lines I had a debug session in SimHub. I think it should be possible to extract the type of the "generic" properties like `DataCorePlugin.*` (i.e. not `dcp.*`). Give me some time please.

**Comment by pre-martin** [comment]
Fix for this is on the way: https://github.com/pre-martin/SimHubPropertyServer/pull/38

**Comment by pre-martin** [comment]
Solved with https://github.com/pre-martin/SimHubPropertyServer/releases/tag/v1.9.6
