### ISSUE TITLE
Assign of Buttons not possible from SD Simhub Plugin to Property Server

### ISSUE THREAD

**Issue by IgnazMK** [pre-martin/StreamDeckSimHubPlugin#121]
Simhub with Licence, also Streamdeck Software on Win11Pro always the latest Version.
Property Server in Simhub installed, Simhub Plugin in SD also in a own profile running 
When i want to bind something, i dont get a button assingned, like even a trigger to Global controls
In SH the "pick a control" is open, Property server is Enabled, when i press a button on the SD nothing happens.
Always waiting for Input

![SD](https://github.com/user-attachments/assets/28cf0f70-fcc8-436d-bdce-ef0641027aa1)
I tryed to assign Motion Global Controls  to test them, but did also a lot of other things to check 

[PropertyServer.log](https://github.com/user-attachments/files/16806159/PropertyServer.log)
[StreamDeckSimHub.log](https://github.com/user-attachments/files/16806167/StreamDeckSimHub.log)

Also i do a new install of SD and Plugins

**Comment by pre-martin** [comment]
It looks like the buttons in Stream Deck are completely unconfigured.

Define an unique value for the field "SimHub Control" like in this screenshot:
![grafik](https://github.com/user-attachments/assets/f89b1053-ba01-4d1f-bdd4-91d447ff923f)

Then it should be possible to assign this Stream Deck button to a SimHub control:
![grafik](https://github.com/user-attachments/assets/733db4d0-82e5-45ac-9db9-1559b42674c7)

This is an example from the "Controls" tab of the ShakeIt Wind plugin.

**Comment by IgnazMK** [comment]
Sometimes it is so easy, you can't see it and take hours of Time...
Yes, this causes the Problem, and now it works.
Thanks a lot for your fast help!
