### ISSUE TITLE
Yellow triangle "!" on Hotkey

### ISSUE THREAD

**Issue by gmoska** [pre-martin/StreamDeckSimHubPlugin#39]
Hi all,

Unfortunatelly, after a new OS (windows) instalation, this week. I can not use this great feature on my streamdeck. 
All the time, on version  1.4.16.1521, after click on the button linked with the hotkey nothing happens and the button only shows a Yellow Triangle. 

Could you help me to double check what am I doing wrong?

many thanks in advance for this nice feature e atention
Gustavo

**Comment by pre-martin** [comment]
Can you verify that .NET Runtime 6.0 is installed on your PC? Just follow the link in the section "Installation" - it leads to Microsoft. Download and install this runtime please.

Be sure to use the following link of the project: https://github.com/pre-martin/StreamDeckSimHubPlugin/tree/v1.4.16.

**Comment by gmoska** [comment]
> Can you verify that .NET Runtime 6.0 is installed on your PC? Just follow the link in the section "Installation" - it leads to Microsoft. Download and install this runtime please.
> 
> Be sure to use the following link of the project: https://github.com/pre-martin/StreamDeckSimHubPlugin/tree/v1.4.16.

Hi,
Everything is working properlly right now. many thanks!

**Comment by pre-martin** [comment]
I'm glad it works.

BTW: I release a new version just this afternoon. It allows to display values on the buttons :-)
