### ISSUE TITLE
Display format string for session time

### ISSUE THREAD

**Issue by mfilej** [pre-martin/StreamDeckSimHubPlugin#91]
Hi, I'm having lots of fun with this, thanks for making it.

One thing I wasn't able to figure out from the docs is how to format the session time.

I'm displaying the property `DataCorePlugin.GameData.SessionTimeLeft` which is showing up in HH:MM:SS.xxxxx, but I'd like to keep it simple with just HH:MM. I'm sure I'm missing something obvious!

**Comment by pre-martin** [comment]
https://github.com/pre-martin/SimHubPropertyServer/issues/34 has to be done before.

**Comment by pre-martin** [comment]
Current behavior with 1.9.x:
![grafik](https://github.com/pre-martin/StreamDeckSimHubPlugin/assets/5703553/1d428908-d208-4307-9362-46900f1939ab)

New with format string `:mm\:ss`:
![grafik](https://github.com/pre-martin/StreamDeckSimHubPlugin/assets/5703553/0ba4eee2-1af4-497e-9185-f300bac9a9f0)

Or the same time left with `:hh\:mm`:
![grafik](https://github.com/pre-martin/StreamDeckSimHubPlugin/assets/5703553/0ee4779f-dc2a-43d3-9f2b-2208c9296ca3)

I can release the new versions of both plugins soon :-) Just some more testing and maybe another improvement I found while adding support for TimeSpan.

**Comment by mfilej** [comment]
Absolutely amazing. Thank you!
