### ISSUE TITLE
Custom flag button and flashing buttons.

### ISSUE THREAD

**Issue by pnbr0014** [pre-martin/StreamDeckSimHubPlugin#95]
Hey this plugin is amazing so far! I have a feature suggestion. Custom flag buttons allow us to change what is displayed for each flag type.

Also what's the possibility of being able to make a button flash so for example for ignition off state have it flash on and off at an interval set by the user. Or am I better off assigning a flashing gif to the off state?

Bruce.

**Comment by pnbr0014** [comment]
Sounds good! So how do you call up different flag colors right now? The stream deck supports dynamic icons like how their volume controls work so there must be a way to leverage that. My initial thought was to create an icon with the colour of the flag blue red yellow checkered etc. and let the stream deck use that as a payload but I have no idea how that would work since currently thy only support 2 icon states. 

I just got the XL and I'm just very excited about everything it can do haha.

**Comment by pre-martin** [comment]
Good news: I started with your feature request "Custom flag buttons".

Not so good news: It is not possible to send animated GIFs from a plugin to the Stream Deck. Only the Stream Deck software itself can do this, if you use "Set [Icon] from File". But then this image is static and cannot be changed during runtime.

So flashing buttons will be more complicated to implement.

**Comment by pre-martin** [comment]
- Custom flags: issue #123 
- Flashing flags: issue #143

**Comment by pre-martin** [comment]
Closing this request, because both sub tasks have been implemented. They will be released with version 1.13.
