### ISSUE TITLE
About operations when using Dial Stacks

### ISSUE THREAD

**Issue by shinchiba** [pre-martin/StreamDeckSimHubPlugin#96]
Hi.
Thank you very much for this great plugin.

I use this plugin with Stream Deck Plus.
If I use "Dial Stacks", the functions assigned to the press button will not be available.
Therefore, I would like to be able to substitute the press button by tapping the Touch strip.
Are there any plans to support Touch strip tapping?

Thank you for your cooperation.

**Comment by pre-martin** [comment]
Hi.

Yes, Touch Tap is still missing. But it doesn't take much effort to implement this. Should be possible to add this soon.

**Comment by shinchiba** [comment]
Thank you for your reply. I'm looking forward to it.

**Comment by pre-martin** [comment]
Two solutions are possible:

1. "Touch Tap" uses the same configuration as "Dial Press". So you would configure "Dial Press" in my plugin and then you could press the knob our touch the touch strip - both would behave the same.
2. I add a new config section "Touch Tap" which is independent from "Dial Press". So you could configure two different actions (or in your case only configure "Touch Tap" and leave "Dial Press" alone).

I think I will implement no. 2.
